channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.1.2
- pip:
  - mlflow==2.19.0
  - astunparse==1.6.3
  - cloudpickle==3.1.0
  - colorama==0.4.6
  - dill==0.3.8
  - google-cloud-aiplatform==1.74.0
  - google-cloud-bigquery-connection==1.17.0
  - google-cloud-bigquery-storage==2.27.0
  - google-cloud-bigtable==2.27.0
  - google-cloud-datastore==2.20.2
  - google-cloud-firestore==2.19.0
  - google-cloud-functions==1.19.0
  - google-cloud-iam==2.17.0
  - google-cloud-language==2.16.0
  - google-cloud-pubsub==2.27.1
  - google-cloud-translate==3.19.0
  - google-colab==1.0.0
  - google-genai==0.3.0
  - google-generativeai==0.8.3
  - httpcore==1.0.7
  - jaraco-collections==5.1.0
  - numpy==1.26.4
  - optree==0.13.1
  - orjson==3.10.12
  - pandas==2.2.2
  - pathlib==1.0.1
  - pydot==3.0.3
  - timm==1.0.12
  - torch==2.5.1
  - wandb==0.19.1
name: mlflow-env
